env:
    NO_INTERACTION: 1

steps:
    - label: ":php: 7.3 amd64"
      command: ./.buildkite/build_extension.sh 7.3
      agents:
          phpbuild: "no-debug"
          queue: "build"

    - label: ":php: 7.2 amd64"
      command: ./.buildkite/build_extension.sh 7.2
      agents:
          phpbuild: "no-debug"
          queue: "build"

    - label: ":php: 7.1 amd64"
      command: ./.buildkite/build_extension.sh 7.1
      agents:
          phpbuild: "no-debug"
          queue: "build"

    - label: ":php: 7.0 amd64"
      command: ./.buildkite/build_extension.sh 7.0
      agents:
          phpbuild: "no-debug"
          queue: "build"

    - label: ":php: 7.3-zts amd64"
      command: ./.buildkite/build_extension.sh 7.3-zts
      agents:
          phpbuild: "no-debug"
          queue: "build"

    - label: ":php: 7.2-zts amd64"
      command: ./.buildkite/build_extension.sh 7.2-zts
      agents:
          phpbuild: "no-debug"
          queue: "build"

    - label: ":php: 7.1-zts amd64"
      command: ./.buildkite/build_extension.sh 7.1-zts
      agents:
          phpbuild: "no-debug"
          queue: "build"

    - label: ":php: 7.3 i386"
      command: ./.buildkite/build_extension.sh 7.3
      agents:
          phpbuild: "no-debug"
          queue: "build"
          arch: "i386"

    - label: ":php: 7.2 i386"
      command: ./.buildkite/build_extension.sh 7.2
      agents:
          phpbuild: "no-debug"
          queue: "build"
          arch: "i386"

    - label: ":php: 7.1 i386"
      command: ./.buildkite/build_extension.sh 7.1
      agents:
          phpbuild: "no-debug"
          queue: "build"
          arch: "i386"

    - label: ":php: 7.0 i386"
      command: ./.buildkite/build_extension.sh 7.0
      agents:
          phpbuild: "no-debug"
          queue: "build"
          arch: "i386"

    - label: ":php: 7.3-zts i386"
      command: ./.buildkite/build_extension.sh 7.3-zts
      agents:
          phpbuild: "no-debug"
          queue: "build"
          arch: "i386"

    - label: ":php: 7.2-zts i386"
      command: ./.buildkite/build_extension.sh 7.2-zts
      agents:
          phpbuild: "no-debug"
          queue: "build"
          arch: "i386"

    - label: ":php: 7.1-zts i386"
      command: ./.buildkite/build_extension.sh 7.1-zts
      agents:
          phpbuild: "no-debug"
          queue: "build"
          arch: "i386"

    - wait

    - label: ":package::debian: amd64"
      command: ./package_extension.sh
      agents:
          queue: "build"
          phpbuild: "no-debug"
          arch: "x86_64"
